Add utility upload function
ComotionLabs/comotion-sdk pull request #74
Opened 2024-10-21 10:45 UTC by eba99

New classes created for uploads to v1 and v2 lake, as well as modifying read_and_upload_file_to_dash function to do the following: 
- Determine which version a client is on (can also be specified)
- Upload file to the correct endpoint

Effect is that users should not have to make changes to their uploads, unless they are using an application client and secret.  These must be passed as args in the function to retrieve upload credentials.

2024-10-22 15:35 UTC, timalive requested changes

2024-10-22 15:35 UTC, timalive commented on Pipfile
> +comotion-sdk = {file = ".", editable = true}
Cant have this here, as it creates circular references.  Having it in the dev package is fine for local testing.

2024-10-22 15:35 UTC, timalive commented on Pipfile
> +python-dotenv = "*"
not sure why you require this?

2024-10-22 15:35 UTC, timalive commented on src/comotion/dash.py
> +    def upload_file(self, file: Union[str, io.FileIO], file_upload_response: FileUploadResponse):
is there a unit test for this?

2024-10-22 15:35 UTC, timalive commented on src/comotion/dash.py
> +class Dash_v1_Easy_Upload():
why do you need a whole class for v1 and v2.  PErhaps combine and call it UploadUtilities?

2024-10-22 15:35 UTC, timalive commented on src/comotion/dash.py
> +class Dash_v1_Easy_Upload():
also, unit tests

2024-10-22 15:35 UTC, timalive commented on src/comotion/dash.py
add new parameters to comments

2024-10-22 15:35 UTC, timalive commented on src/comotion/dash.py
why would you have to supply a load to this function?

2024-10-22 15:35 UTC, timalive commented on src/comotion/dash.py
> +            if migration.status().full_migration_status == 'Completed': # What about for new clients who start on v2 lake?  Will status be complete?
Good question. Until further notice, we must run a migration on all new clients as part of setting them up.

2024-10-23 09:17 UTC, timalive requested changes

2024-10-23 09:17 UTC, timalive commented on src/comotion/dash.py
> +    def upload_file(self, file: Union[str, io.FileIO], file_upload_response: FileUploadResponse):
add file_upload response as an optional. IF not supplied then automatically fetch.  Supply filekey as an optional.  Also, boolen option to use the file name as filekey.

2024-10-23 09:17 UTC, timalive commented on src/comotion/dash.py
> +class Dash_v1_Easy_Upload():
upload utilities

2024-10-23 09:17 UTC, timalive commented on src/comotion/dash.py
doc string

2024-10-23 09:17 UTC, timalive commented on src/comotion/dash.py
> +    def v1_upload_csv(
doctring. v1 will be deprecated.

2024-11-02 18:02 UTC, timalive requested changes
I think we should ask Kevin and Daniel to give us a few hours to test this.

2024-11-02 18:02 UTC, timalive commented on Pipfile
> +exceptiongroup = "*"
interesting. where are you using this

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +    If you wish to work with an existing load, then supply load_id only the load_id parameter
this sentence does not make sense. Probably wanted to say "then supply only the load_id parameter."?

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        load = Load(config = DashConfig(Auth('orgname')),
we use "Sphynx" for documentation. that automatically converts these docstrings into proper docs.  This example should be a "literal block".  You can see how to do that [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks).  Note that it is simply adding a double ::

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +            large files as this may increase the duration of upload significantly.
nice

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +            will be saved to the location specified. This is useful for testing.
nice

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        lowerlevel_load_keys = [key for key in lowerlevel_load_sig.parameters.keys()]
I learnt something

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +                }
clever

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        Uploads a file to an S3 bucket using a presigned URL.
update this comment... should be file, or dataframe or directory depending on what is provided

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        file : Union[str, io.FileIO]
should be "data"

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        file : Union[str, io.FileIO]
maybe change it to "data_source"

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        file_key : str, optional
is this only in the case of a file?

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        file_key : str, optional
saying "under which the file"  mayh be confusing for other formats

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        file_upload_response : FileUploadResponse, optional
will need more info here.   I am thinking we should kick it out into another function.  This will confuse python analysts

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        >>> load = Load(dashconfig)
probably better to use a literal block

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +            return upload_reponse
cant see where you are dealing with the upload a whole directory option?

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +
needs a thorough docstring. Sholuld include a good overview of the class and how to use it.

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        """Return a new DashConfig object with the auth_token provided to DashBulkUploader."""
the name of this function not 100% cleaer I think

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +
you can maybe include an example of using the class here

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +    def add_data_to_load(
how is this more functionality than what should be available in the load class?

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        max_workers: int = 5
max workers should default to CPU's available x2 I think.
here is an idea of code for this:
```
if max_workers is None:
  num_cores = os.cpu_count()
  max_workers = num_cores * 2 
```

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        table_name: str,
why does this have to be specific to one table? Cant we execute loads to a number of tables?

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +            with ThreadPoolExecutor(max_workers=max_workers) as upload_executor:  # Use multi-threading to speed up uploads
actually, I see this from the [threadpoolexecutor docs.](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor)
 if max_workers not supplied, we can just get threadpoolexecutor to figure out how many it should run.
`  Changed in version 3.5: If max_workers is None or not given, it will default to the number of processors on the machine, multiplied by 5, assuming that [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) is often used to overlap I/O instead of CPU work and the number of workers should be higher than the number of workers for [ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor).`

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +    def get_load_info(self, max_workers: int = 5):
see my previuos comment. we should remove the default.

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        with ThreadPoolExecutor(max_workers=max_workers) as status_executor:
what if we run into rate limit exceeded probelms on the API. we should have a quick chat about that scenario.

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        load: Load,
why not just add this function to the Load class?

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +    def upload_file(
why not just add this to the load class?

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        A unique key for the file being uploaded. If not provided, a key will be generated.
we should ad dmore explanation to this file_key comment.  Why do we have a file key? Something like "file key helps ensure that the same file is not uploaded twice"

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +    - Upload them to Dash
add a general note here about how this will check if its v1 or v2.  And a link to an explanation of v1 and v2.

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        Uploads a file to an S3 bucket using a presigned URL.
consider adding handling of a df iterator - lkike what reading a chunked CSV produces in panda.s

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        of the service client.
we can include a link to a page - we must have a proper explanation in the docs on service client and how it works with loads.

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        The data model version to use for the upload. If not specified, the function will determine the version.
we should say that this should only be used in exceptional circumstances.

2024-11-02 18:02 UTC, timalive commented on src/comotion/dash.py
> +        The entity type for authentication.
?

2025-03-24 12:15 UTC, eba99 commented
The following has been changed in this branch:
- The read_and_upload_file_to_dash function was re-written to support both the v1 and v2 data model.  This is to allow for smoother transition for clients after migrating the data model
- The Load class was enhanced to allow easy uploads from a pandas dataframe, various file types, a directory and a dash.Query object
- A DashBulkUploader class was created to allow for easy uploading to multiple lake tables at once.  This uses the load class and uses a dictionary to manage several loads with multi-threading implemented to improve upload performance.

So essentially the old upload function has been modified to be backwards-compatible, in a way.  The read_and_upload_file_to_dash function uses the v1 api if not migrated, and the v2 load mechanism via the DashBulkUploader otherwsie.  The DashBulkUploader uses the Load class, which will be the core, public-facing class to upload data to Dash.  So everything flows through the load class eventually anyway to ensure upload behaviour is consistent.

The SDK documentation was also updated substantially, to add new examples to the overview and refresh the documentation for the new classes created in the dash.py source file.

2025-03-26 07:49 UTC, timalive requested changes
see my comments on review.

2025-03-26 07:49 UTC, timalive commented on Pipfile
> +comotion-sdk = {file = ".", editable = true}
@eba99 this still needs to be resolved

2025-03-26 07:49 UTC, timalive commented on Pipfile
> +python-dotenv = "*"
Still awaing response on this one

2025-03-26 07:49 UTC, timalive commented on src/comotion/dash.py
> +    def upload_file(self, file: Union[str, io.FileIO], file_upload_response: FileUploadResponse):
awating answer

2025-03-26 07:49 UTC, timalive commented on src/comotion/dash.py
> +    def upload_file(self, file: Union[str, io.FileIO], file_upload_response: FileUploadResponse):
still to be resolved

2025-03-26 07:49 UTC, timalive commented on src/comotion/dash.py
> +class Dash_v1_Easy_Upload():
still awaiting response on this

2025-03-26 07:49 UTC, timalive commented on src/comotion/dash.py
> +    def v1_upload_csv(
also this

2025-03-26 07:49 UTC, timalive commented on src/comotion/dash.py
see above

2025-03-26 14:31 UTC, eba99 commented on Pipfile
> +python-dotenv = "*"
Has since been removed

2025-03-26 14:32 UTC, eba99 commented on src/comotion/dash.py
> +class Dash_v1_Easy_Upload():
This has been removed and is only using the v1_upload_csv class.

2025-03-26 14:32 UTC, eba99 commented on Pipfile
> +comotion-sdk = {file = ".", editable = true}
Has been removed and will be tested with new pipfile

2025-03-26 21:32 UTC, eba99 commented on Pipfile
> +comotion-sdk = {file = ".", editable = true}
Ok should now be removed

2025-03-26 21:52 UTC, eba99 commented on src/comotion/dash.py
> +    def upload_file(self, file: Union[str, io.FileIO], file_upload_response: FileUploadResponse):
Unit test added in latest commit, for this and upload_query as that was also missing.

2025-03-26 22:28 UTC, eba99 commented on src/comotion/dash.py
These arguments have since been removed. Deprecation warning added to v1_upload_csv and read_and_upload_to_dash: https://github.com/ComotionLabs/comotion-sdk/commit/4d91d978ce5d35e09cc0b95ac4352c552e28ee5a

2025-03-26 23:12 UTC, eba99 commented on src/comotion/dash.py
> +    def upload_file(self, file: Union[str, io.FileIO], file_upload_response: FileUploadResponse):
Added with unit tests: https://github.com/ComotionLabs/comotion-sdk/commit/89c506d593e9c940cf210bf5400aac0dc4fee757

2025-03-26 23:13 UTC, eba99 commented on src/comotion/dash.py
> +    def v1_upload_csv(
This has been resolved as these args are no longer in the function. Docstring improved.

2025-03-27 10:06 UTC, timalive submitted a review, later dismissed

2025-03-27 10:21 UTC, eba99 commented on src/comotion/dash.py
> +        of the service client.
A link has since been added to docstring. Is this sufficient?

2025-03-27 10:21 UTC, eba99 commented on src/comotion/dash.py
> +        The data model version to use for the upload. If not specified, the function will determine the version.
This has been added

2025-03-27 12:12 UTC, timalive approved these changes

2025-03-27 12:14 UTC, timalive approved these changes

2025-03-27 12:17 UTC, merged